matrix:
  include:
    - language: node_js
      node_js:
        - 10.15.3
      before_script:
        - cd frontend/inseption
        - npm install
      deploy:
        provider: gae
        keyfile: frontend.json
        project: inseption
        on:
          branch: master

    - language: java
      cache:
       directories:
       - "$HOME/google-cloud-sdk/"
      before_script:
        - cd restful-web-services
      after_success:
        - cd src && cd main && cd resources && sed -i '$ d' application.properties && cd .. && cd .. && cd ..
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version
        - gcloud auth activate-service-account --key-file backend.json
        - gcloud config set project inseption-backend
        - mvn appengine:deploy -Dmaven.test.skip=true
        - echo "Deploy complete."
